version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./public:/var/www/app/public:ro
    depends_on:
      - app
    ports:
      - "8010:80" # you may change port 8010 to your needs do not touch port 80
      #- "4413:443"
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:5
    env_file: env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./public:/var/www/app/public:rw,delegated
      - ./storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db    
    networks:
      - invoiceninja

  db:
    image: mysql:8
    ports:
      - "3305:3306"
    restart: always
    env_file: env
    volumes:
      - ./mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: env
    ports:
      - "8191:80"
    networks:
      - invoiceninja      

networks:
  invoiceninja:
